<?xml version="1.0"?>
<robot name="robot_urdf" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="dimensional_properties.xacro" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${wheel_radius}" />
            </geometry>
            <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
            <material name="Orange_Red">
                <color rgba="1 0.325 0.286 1" />
            </material>
        </visual>
    </link>

    <xacro:macro name="wheel" params="location">
        <link name="${location}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${(wheel_radius)}" length="${wheel_width}" />
                </geometry>
                <origin xyz="0 ${wheel_width} 0" rpy="${pi / 2.0} 0 0" />
                <material name="Violet_Blue">
                    <color rgba="0.196 0.2902 0.698 1">
                    </color>
                </material>
            </visual>
        </link>
    </xacro:macro>
    
    <xacro:wheel location="front_left" />
    <xacro:wheel location="back_left" />
    <xacro:wheel location="front_right" />
    <xacro:wheel location="back_right" />

    <joint name="front_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_left_wheel" />
        <origin xyz="${(base_length)*0.25} ${(base_width/2.0)-0.015} ${wheel_radius}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="back_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="back_left_wheel" />
        <origin xyz="${(-base_length)*0.25} ${((base_width/2.0)-0.015)} ${wheel_radius}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>
    
     <joint name="front_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_right_wheel" />
        <origin xyz="${(base_length)*0.25} ${(-base_width/2.0)-0.045} ${wheel_radius}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="back_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="back_right_wheel" />
        <origin xyz="${-(base_length)*0.25} ${(-base_width/2.0)-0.045} ${wheel_radius}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>
 
</robot>
